@host=http://localhost:3000

# .env DATABASE_HOST 확인
GET {{host}}

###

# 회원 가입 메일
POST {{host}}/users
Content-Type: application/json

{
  "name": "JINTAE PARK",
  "email": "12161733@inha.edu",
  "password": "PASSWORD"
}

###

# email인증
POST {{host}}/users/email-verify?signupVerifyToken=test_token

###

#로그인
POST {{host}}/users/login
Content-Type: application/json

{
  "email": "YOUR_EMAIL",
  "password": "PASSWORD" 
}

###

# 회원 정보 조회
GET {{host}}/users/user-id


